name: demo-action

on:
  push:
      branches: main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          
          - name: run a sample job
            run: echo Hello world
  
