name: demo-action

on:
  push:
      # branches: main
  issues:
      types: [opened]
  workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          
          - name: run a sample job
            run: echo Hello world

          - name: Upload artifact
          - uses: actions/upload-artifact@v4
            with:
              name: build=artifact
              path: ${{github.workspce}}
